# Generated by Django 6.0.5 on 2026-06-07 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["created"]},
        ),
    ]
