# Generated by Django 6.0.5 on 2026-06-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_profile_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profiles/user.png",
                null=True,
                upload_to="profiles/",
            ),
        ),
    ]
