# Generated by Django 6.0.5 on 2026-05-31 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_alter_project_options_review_owner_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-vote_ratio", "-vote_total", "title"]},
        ),
    ]
